Repository AlDevCR/local_match, pull requests merged in 2019-01, with the labels that each got.

#15 Add Dockerfile
  Dockerfile
Labels: needs rework

#16 Add interface to manage events
  localMatchApp/forms/homewindow.ui
  localMatchApp/headers/homewindow.h
  localMatchApp/headers/mainwindow.h
  localMatchApp/resources/images/deleteIcon.svg
  localMatchApp/resources/images/modifyIcon.svg
  localMatchApp/resources/images/newImageIcon.svg
  localMatchApp/resources/images/noImageIcon.svg
  localMatchApp/resources/resources.qrc
  localMatchApp/sources/homewindow.cpp
Labels: needs review

#17 Delete config options in Qt build
  Dockerfile
Labels: to be merged

#18 Add functionalities of commercial user to add and update events
  localMatchApp/forms/homewindow.ui
  localMatchApp/headers/DatabaseManager.h
  localMatchApp/headers/GeneralEvent.h
  localMatchApp/headers/homewindow.h
  localMatchApp/resources/images/noEvents.svg
  localMatchApp/resources/resources.qrc
  localMatchApp/sources/DatabaseManager.cpp
  localMatchApp/sources/GeneralEvent.cpp
  localMatchApp/sources/homewindow.cpp
Labels: needs review
